version: "3.8"

services:
  airflow-init:
    image: apache/airflow:2.7.3
    restart: "no"
    env_file: .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: >
      bash -c "airflow db upgrade &&
               airflow users create --username ${_AIRFLOW_WWW_USER_USERNAME} --firstname Airflow --lastname Admin --role Admin --email admin@example.com --password ${_AIRFLOW_WWW_USER_PASSWORD}"

  webserver:
    image: apache/airflow:2.7.3
    env_file: .env
    depends_on:
      - airflow-init
      - statsd-exporter
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: webserver

  scheduler:
    image: apache/airflow:2.7.3
    env_file: .env
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler

  statsd-exporter:
    image: prom/statsd-exporter:latest
    ports:
      - "9102:9102"       # HTTP /metrics for Prometheus
      - "9125:9125/udp"   # StatsD UDP listener
    volumes:
      - ./statsd_mapping.yml:/tmp/statsd_mapping.yml:ro
    command: ["--statsd.mapping-config=/tmp/statsd_mapping.yml"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
